some basic ui stuff
s5bug/artg120-final pull request #3
Opened 2023-05-23 21:16 UTC by anranlee99

pls fix merge

2023-05-23 23:19 UTC, anranlee99 commented
no conflict now?

2023-05-23 23:24 UTC, s5bug requested changes

2023-05-23 23:24 UTC, s5bug commented on src/main.ts
> +                repeat: 3
Essentially what you should be doing is `sync`ing all the synths to the `Transport`, and then only changing them when the underlying music changes. Essentially, what you have on the `Transport` is data-driven, and then all the inputs control the `Transport`.

```ts
// one time
this.synth.sync() // sync the synth to the transport
this.synth.triggerAttackRelease("C4", "8n", 0)
this.synth.triggerAttackRelease("C4, "8n", "2n")
this.synth.triggerAttackRelease("C4", "8n", "1n")
```
```ts
// every click
Tone.Transport.stop()
Tone.Transport.start()
```

2023-05-23 23:24 UTC, s5bug commented on src/main.ts
> +    },
Is physics used here at all?

2023-05-28 23:57 UTC, s5bug requested changes

2023-05-28 23:57 UTC, s5bug commented on src/main.ts
> +                    i++
This is still incorrect:

`sync` and `triggerAttackRelease` should only be done once: this puts the notes on the Transport (think of the Transport as a piece of sheet music)

`Transport.start()` and `Transport.stop()` control the musician playing the sheet music, and _these_ are what you should be calling repeatedly

2023-05-30 00:47 UTC, s5bug requested changes

2023-05-30 00:47 UTC, s5bug commented on src/main.ts
> +            seq.loop = 1;
This should be moved to after the `sync` instruction as to not be done every time the mouse is pressed

2023-05-30 00:47 UTC, s5bug commented on src/main.ts
> +
Either rename to `_pointer` or add a useless line `pointer;` to silence the Typescript warning

2023-06-04 19:26 UTC, s5bug approved these changes

2023-06-04 19:26 UTC, merged